### PR TITLE
Feature newexclifetimes

### PR DESCRIPTION
**Pull request by rreho**
Merge request related to #40 . 
I created a new file and class for `ExcitonLifetimes`.
This method, computes the exciton lifetimes and radiative decay as described in 
https://pubs-acs-org.proxy.library.uu.nl/doi/full/10.1021/acs.nanolett.8b01114 

A tutorial is available in the new branch `feature-documentation`. I need to create a new merge request for this branch too. I would like to keep the -doc in a separate branch.

### CODE REVIEW

**Comment by palful** [comment]
Ciao Riccardo, thank you for the new pull request. I can't find the new file with the class `ExcitonLifetimes`, is it possible that it wasn't pushed?

**Comment by rreho** [comment]
I just pushed it, I hope it's visible otherwise I might create a new merge request

**Comment by palful** [comment]
I still don't see it :( 

The commits to the PR branch should in principle automatically update, but actually the last commit I see here is from 26 June

**Comment by palful** [comment]
Thanks! I'm merging it in the bug-fixes, I will make a few cosmetic changes and pass it to the master.

I have three questions:
1. You can select "velocity" or "length" gauge. I thought this choice was already pre-determined in the exciton residuals, since they are computed with the dipoles already in a certain gauge (including dividing by the electronic energies in the velocity case). Why re-apply it here? 
2. In the comments, it's written "get exciton lifetimes in 2D assuming the plane is on x,y", and the field direction is never explicitly used. The orientation of the exciton dipole is embedded already in the residuals computed with a specific `BLongDir`, I think. So this means that it is assumed that, if a calculation was made with `BLongDir=[1,1,0]` (or any other direction) then the direction of the outcoming photon would be the same, right? This means that the photon can only be emitted in the direction of the exciton dipole. Is this ok to use for any BSE calculation?
3. `q0_norm` is set to `1e-5`. I suspect that in the 2D case, if the Coulomb cutoff was used, it should probably be using the value of `yexcdb.q_cutoff`, right?

**Comment by rreho** [comment]
This is a minimal implementation of the lifetimes, and I did not remove comments related to the full implementation. I am sorry for the confusion. 

1. Not sure, what I remember is that I had to scale differently the units and some factors like `q0norm=1e-5` to be consistent among two gauges.
2. Yes, I think you are right. But if I recompute the exciton dipoles from scratch, I can select the direction internally in `yambopy` so that I don't have to relaunch a `Yambo` calculation. That's one of the feature that is not available in this minimal branch.
3. I think that this line in `get_chi`, `if self.q_cutoff is not None: q0norm = self.q_cutoff` takes it into account. But I do remember that in `exclifetimes.py` the method `get_exciton_lifetimes` needs this factor, and it depends on the gauge. I suspect that `self.q_cutoff` contains `q0_norm` plus other factors. I think that in `get_exciton_lifetimes` I am, in practice, recomputing `self.q_cutoff`.

**Pull request merged**
